import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "./Component/navabar";
import Provider from "./Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Js Project",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${geistSans.variable} antialiased`}>
          <Navbar />
          {children}
        </body>
      </Provider>
    </html>
  );
}
